### ISSUE TITLE
Could you please post any running results of this repo for reference

### ISSUE THREAD

**Issue by haolibai** [pppppM/mmsegmentation-distiller#3]
Hi,

Many thanks for your effort to share this repo~ May I know if you can post some running results with this repo  for reference? So that we are able to know if our results are reasonably good.

**Comment by pppppM** [comment]
Thanks for your attention.
This repo is just an example of how to distill a model by MMSegmentation.
The experiments in the semantic segmentation part of our paper did not use this repo, and my co-author will release the code used in this part later.
If you are interested in our experiment results, I will notify you as soon as possible after the code release.
And I'm developing a general model compress toolbox containing all the repo features and will release it later, so, the repo will not be maintained.

**Comment by haolibai** [comment]
Thanks for your quick response. Look forward to your results.
